name: async_retriever-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiosqlite
  - aiohttp >=3.8.1
  - brotli
  - cchardet
  - cytoolz
  - nest-asyncio
  - aiohttp-client-cache >=0.7.3
  - ujson

  - pytest-cov
  - pytest-xdist
  - psutil
