name: async_retriever-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - orjson
  - setuptools

  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky
