name: async_retriever-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiohttp
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson
  - setuptools

  - coverage
  - tomli
  - pytest-clarity
  - pytest-sugar
  - pytest-xdist
  - psutil
  - ward
