name: async_retriever-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - setuptools

  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - orjson

  # dev deps
  - codespell
  - nox
  - pre-commit
  - psutil
  - pytest
  - pytest-clarity
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - setuptools-scm

  # ward deps
  - tomli
  - markupsafe
  - click-completion
  - click-default-group
  - colorama
  - commonmark
  - cucumber-tag-expressions
  - jinja2
  - pprintpp
  - pygments
  - rich
  - shellingham

  - pip
  - pip:
    - ward
    - git+https://github.com/cheginit/async_retriever.git
